version: '2'
services:
  couchdb:
    image: frodenas/couchdb:1.6
    environment:
      COUCHDB_USERNAME: "uname"
      COUCHDB_PASSWORD: "passwd"
      COUCHDB_DBNAME: "pollstr"
    ports:
      - "5984:5984"
  worker:
    build: .
    env_file: .env
    environment:
      COUCHDB_URL: "uname:passwd@couchdb:5984/pollstr"
    links:
      - couchdb
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "8000:8000"
    depends_on:
      - couchdb
